// <auto-generated />
using System;
using AchillesTest.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AchillesTest.Migrations
{
    [DbContext(typeof(UniversidadDbContext))]
    [Migration("20260220210122_AddStoredProcedure")]
    partial class AddStoredProcedure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AchillesTest.Domain.Entities.Asignacion", b =>
                {
                    b.Property<int>("IdAsignacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAsignacion"));

                    b.Property<DateTime>("Fect_asi")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdDocente")
                        .HasColumnType("int");

                    b.HasKey("IdAsignacion");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdDocente");

                    b.ToTable("TB_ASIGNACION", (string)null);
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Curso", b =>
                {
                    b.Property<int>("IdCurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCurso"));

                    b.Property<string>("Dura_cur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nomb_cur")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCurso");

                    b.ToTable("TB_CURSO", (string)null);
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Distrito", b =>
                {
                    b.Property<int>("IdDistrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDistrito"));

                    b.Property<int>("Idprovincia")
                        .HasColumnType("int");

                    b.Property<string>("Nomb_dis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdDistrito");

                    b.HasIndex("Idprovincia");

                    b.ToTable("TB_DISTRITO", (string)null);
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Docente", b =>
                {
                    b.Property<int>("IdDocente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDocente"));

                    b.Property<string>("Apel_doc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdProfesion")
                        .HasColumnType("int");

                    b.Property<string>("Nomb_doc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfesionIdProfesion")
                        .HasColumnType("int");

                    b.HasKey("IdDocente");

                    b.HasIndex("ProfesionIdProfesion");

                    b.ToTable("TB_DOCENTE", (string)null);
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Estudiante", b =>
                {
                    b.Property<int>("IdEstudiante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstudiante"));

                    b.Property<string>("Apel_est")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDistrito")
                        .HasColumnType("int");

                    b.Property<string>("Nomb_est")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdEstudiante");

                    b.HasIndex("IdDistrito");

                    b.ToTable("TB_ESTUDIANTE", (string)null);
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Matricula", b =>
                {
                    b.Property<int>("IdMatricula")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMatricula"));

                    b.Property<DateTime>("Fech_mat")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCurso")
                        .HasColumnType("int");

                    b.Property<int>("IdEstudiante")
                        .HasColumnType("int");

                    b.HasKey("IdMatricula");

                    b.HasIndex("IdCurso");

                    b.HasIndex("IdEstudiante");

                    b.ToTable("TB_MATRICULA", (string)null);
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Profesion", b =>
                {
                    b.Property<int>("IdProfesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfesion"));

                    b.Property<string>("Nomb_pro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProfesion");

                    b.ToTable("TB_PROFESION", (string)null);
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Provincia", b =>
                {
                    b.Property<int>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProvincia"));

                    b.Property<string>("Nomb_pro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProvincia");

                    b.ToTable("TB_PROVINCIA", (string)null);
                });

            modelBuilder.Entity("AchillesTest.Domain.StoreProcedure.ProvinciaPopularResult", b =>
                {
                    b.Property<string>("Provincia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalEstudiantes")
                        .HasColumnType("int");

                    b.ToTable("ProvinciaPopularResults");
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Asignacion", b =>
                {
                    b.HasOne("AchillesTest.Domain.Entities.Curso", "Curso")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AchillesTest.Domain.Entities.Docente", "Docente")
                        .WithMany("Asignaciones")
                        .HasForeignKey("IdDocente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Docente");
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Distrito", b =>
                {
                    b.HasOne("AchillesTest.Domain.Entities.Provincia", "Provincia")
                        .WithMany("Distritos")
                        .HasForeignKey("Idprovincia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Docente", b =>
                {
                    b.HasOne("AchillesTest.Domain.Entities.Profesion", "Profesion")
                        .WithMany("Docentes")
                        .HasForeignKey("ProfesionIdProfesion");

                    b.Navigation("Profesion");
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Estudiante", b =>
                {
                    b.HasOne("AchillesTest.Domain.Entities.Distrito", "Distrito")
                        .WithMany("Estudiantes")
                        .HasForeignKey("IdDistrito")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Distrito");
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Matricula", b =>
                {
                    b.HasOne("AchillesTest.Domain.Entities.Curso", "Curso")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdCurso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AchillesTest.Domain.Entities.Estudiante", "Estudiante")
                        .WithMany("Matriculas")
                        .HasForeignKey("IdEstudiante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Curso", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Distrito", b =>
                {
                    b.Navigation("Estudiantes");
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Docente", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Estudiante", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Profesion", b =>
                {
                    b.Navigation("Docentes");
                });

            modelBuilder.Entity("AchillesTest.Domain.Entities.Provincia", b =>
                {
                    b.Navigation("Distritos");
                });
#pragma warning restore 612, 618
        }
    }
}
